### ISSUE TITLE
Allow oscilloscope output

### ISSUE THREAD

**Issue by D-u-c-k-s-e-l** [ambrosiogabe/MathAnimation#117]
I am currently looking for something that lets me draw on my oscilloscope.

It would be nice if I could export to `.wav` and draw the vectors on my osciliscope.

I've tried [osci-render](https://github.com/jameshball/osci-render) but it's hard to use if you want anything more than a line of text or an icon.

**Comment by D-u-c-k-s-e-l** [comment]
I don't know how to mark this but this is a feature request btw.

**Comment by ambrosiogabe** [comment]
I'm not sure if this is supposed to be a joke or not, but this is definitely something I'm not planning and don't think I'm ever going to prioritize. This project is meant to export predefined animations to a video format and not meant to be used for real-time rendering on arbitrary devices (so Desktop is the only thing I plan on supporting).

**Comment by D-u-c-k-s-e-l** [comment]
This is not a joke but I understand not implementing this.
Have a nice day.
