### ISSUE TITLE
Better GUI

### ISSUE THREAD

**Issue by WongMan58** [ambrosiogabe/MathAnimation#38]
All the features look amazing, but I have to say that the GUI looks not the greatest. 

Some parts the GUI don't look exactly that bad, like the Timeline, but other parts like the title of sections, look awkward. Especially with the scroll boxes.

**Comment by ambrosiogabe** [comment]
Hi, thanks for opening this. I'll link it to this issue #37 since it falls under the same general theming upgrades I have planned.
