### ISSUE TITLE
Windows build does not compile and suggestions

### ISSUE THREAD

**Issue by Pricter** [ambrosiogabe/MathAnimation#40]
This isn't technically a bug. Its a readme related issue. Please add to the first-time compile these fixes.

1. To actually run ./configure for ffmpeg you need to first open a normal msys2 terminal without the "Developer Command Prompt for VS 2022" and run `pacman -S diffutils`. It is complaining that it does not find a program called "cmp" which is a program that comes with diffutils
2. Default make that comes with msys2 is faulty. It gave an error about awk syntax error even though everything was fine. To fix this you have to manually run `pacman -S make` to install make that is not default.
3. You mention that it may take a long time but you can run in parallels using "-j{number of cores to run on}" in make. So you can suggest that if you want to speed it up and have more number of cores then just use `make -j{core count}". Also mention to keep the core count 2 less than the core count of the processor to give space for the OS and other programs. Running on multiple cores can speed up everything to such a huge degree.
4. The user must have msbuild set or specify its exact path and then use the command. The `msbuild ...` wont work.

Hope you update these in the readme about installation for first time

**Comment by ambrosiogabe** [comment]
Hey Mr. Hecker, for this one:

> The user must have msbuild set or specify its exact path and then use the command. The msbuild ... wont work.

`msbuild` will work if you open "Developer Command Prompt for VS 2022" and then run `msys_shell.bat -use-full-path` as listed in the compiler instructions to launch msys2. This screenshot shows me running msys2 after doing this and `cl` works as listed, you shouldn't need to run `msbuild` so it's alright if that command isn't working.

![tmp](https://user-images.githubusercontent.com/24964392/210149973-d5ccae8c-f85e-40ff-9677-a60f3e76559d.PNG)

For your other points I've updated the README and linked it to this issue.
