### ISSUE TITLE
failed to copy imgui.ini

### ISSUE THREAD

**Issue by alexfeed1990** [ambrosiogabe/MathAnimation#51]
**Describe the bug**
Compiling error: 'Error copying file "C:/Users/Andrew/Desktop/MathAnimation/imgui.ini" to "C:/Users/Andrew/Desktop/MathAnimation/build/bin/Release"'

**To Reproduce**
1. compile the project with cmake

**Expected behavior**
i expect it to be able to copy a file

**Screenshots**
![image](https://user-images.githubusercontent.com/76942911/210268050-c6a6ccf9-2d57-4a29-9e48-ee1d3e0b6a9f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - App Version: pull request number 48

**Additional context**

**Comment by ambrosiogabe** [comment]
Sorry about that! CMake support was added today so I expect there to be some issues. I've added a hotfix to the `master` branch so this issue should be fixed now :)
