### ISSUE TITLE
I am dumb and I am trying to compile it

### ISSUE THREAD

**Issue by TheBosoYolo** [ambrosiogabe/MathAnimation#55]
Where do I run this?:
`REM NOTE This will take quite some time to compile
REM To compile it faster you can use `make -j{core count}` instead of `make` where
REM core count is 2 cores less than the number of cores available on your machine
pushd ./Animations/vendor/ffmpeg
./configure \
    --toolchain=msvc \
    --prefix=./build \
    --disable-doc \
    --arch=x86_64 \
    --disable-x86asm 
make 
make install

REM Rename the files to .lib extension to make premake happy
mv ./build/lib/libavcodec.a ./build/lib/libavcodec.lib
mv ./build/lib/libavdevice.a ./build/lib/libavdevice.lib
mv ./build/lib/libavfilter.a ./build/lib/libavfilter.lib
mv ./build/lib/libavformat.a ./build/lib/libavformat.lib
mv ./build/lib/libavutil.a ./build/lib/libavutil.lib
mv ./build/lib/libswresample.a ./build/lib/libswresample.lib
mv ./build/lib/libswscale.a ./build/lib/libswscale.lib
popd`

in msys msys2 or in the vs cmd or where. What file. How. Thanks

**Comment by ambrosiogabe** [comment]
Hi, you need to run this in the `msys2` terminal that was launched  when following step 2.

> To set up a proper environment in MSYS2, you need to run msys_shell.bat from the Visual Studio or Intel Compiler command prompt. To do this:

**Comment by ambrosiogabe** [comment]
I'm going to close this issue for now, but if you feel like this still isn't enough information feel free to comment and let me know and I'll try to update the readme with more clarity.

**Comment by TheBosoYolo** [comment]
Thanks, but I have another issue with cmake, it throws `C:/msys64/usr/bin/cmake.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory` when i run `cmake ..` with msys. Any fox for that?

**Comment by ambrosiogabe** [comment]
Hey for that, you'll want to run `cmake` from a regular Windows command prompt. Sorry about the confusion!

**Comment by TheBosoYolo** [comment]
Okay, now I have the .sln file somewhere and I build it like a normal c code in vs code or somewhere OR there is a .exe to run it

**Comment by ambrosiogabe** [comment]
Yes, now there should be a file `MathAnimationsPrj.sln` in your `build` directory and you can launch that and then press F5 and it should compile it and run the program :)

**Comment by TheBosoYolo** [comment]
oh yea. I compiled it and it ran just fine, just when I run the MathAnimations.exe it throws some error

**Comment by TheBosoYolo** [comment]
idk if it is you that makes the youtube videos, but if it is you, I am impressed. 1st you took 8 months to make this and 2nd you make it look so easy to use, its hard af
