### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by Senne98** [ambrosiogabe/MathAnimation#80]
When I run cmake.. i get this error

````
CMake Error at CMakeLists.txt:3 (project):
  Running

   'nmake' '-?'

  failed with:

   Het systeem kan het opgegeven bestand niet vinden


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/Senne/Desktop/mathanimator/MathAnimation/build/CMakeFiles/CMakeOutput.log".

**Comment by ambrosiogabe** [comment]
Did you make sure to install `yasm` listed in the requirements and add it to your `PATH`?

> * YASM Assembler version 1.2.0 or later
>   * Download the yasm exe from the following [link](http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe)
>    * Rename yasm-*-win64.exe to yasm.exeCopy yasm.exe into a location that is in the PATH

**Comment by Senne98** [comment]
I added an extra path myself, and it still doesn't work. Is it normal that it says i am running windows-10.0.22621 (I am on windows 11)

**Comment by ambrosiogabe** [comment]
Do you also have a C++ compiler installed like MSVC? If not you'll have to install Visual Studio to compile it.

**Comment by Senne98** [comment]
Thanks, I had it on my previous laptop so I assumed I had it on this one aswell.

**Comment by ambrosiogabe** [comment]
No problem! Glad that we were able to get it fixed :)
